header = """
/* 
 * OpenAWS VPN Client FFI Interface
 * Generated C API bindings
 */
#ifndef OPENAWS_VPN_CLIENT_H
#define OPENAWS_VPN_CLIENT_H

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
"""

trailer = """
#ifdef __cplusplus
}
#endif

#endif /* OPENAWS_VPN_CLIENT_H */
"""

# Use C style output
language = "C"
include_guard = "OPENAWS_VPN_CLIENT_H"
tab_width = 4
cpp_compat = true
style = "both"

# Setup header and include options
include_version = false
sys_includes = ["stdbool.h", "stdint.h", "stddef.h"]
no_includes = false
includes = []

# C specific options
fncase = "CamelCase"
prefix = "openaws_"
cpp_compatible_bitfields = true

[export]
include = ["openaws_init", "openaws_connect", "openaws_disconnect", "openaws_get_state", "openaws_get_last_log", "openaws_free_string", "openaws_cleanup"]
prefix = "openaws_"

[export.rename]
"c_char" = "char"

[parse]
parse_deps = false
include = ["openaws_vpn_client"]

[define]
"target_os = android" = "ANDROID"
